config/routes.rb
Rails.application.routes.draw do
  root 'posts#index' do
    resources :posts, only: [:new, :create, :destroy]  
  end

  devise_for :users
  resources 'users'
  
  resources :posts do
    resources :comments, only: [:create, :destroy]  
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  validates :body, presence: true, allow_blank: false
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user, class_name: "User", foreign_key: "user_id"
  has_many :comments, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts
  has_many :comments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_post
  before_action :authenticate_user!

  def create
    @comment = @post.comments.new(comment_params)
    @comment.user_id = current_user.id
    @comment.save
    # redirect_back(fallback_location: root_path)
  end

  def destroy
    @comment = @post.comments.find(params[:id])
    @comment_id = @comment.id
    @comment.destroy
  end

  private 
  def comment_params
    params.require(:comment).permit(:body, :post_id)
  end
  def set_post
    @post = Post.find(params[:post_id])
  end
  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @posts = Post.all.order("created_at DESC")
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:show, :index]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all.order("created_at DESC")
    @post = Post.new
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @comment = Comment.new
    @comments = @post.comments.order("created_at DESC")
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    @post.save
    redirect_back(fallback_location: root_path)
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:status, :user_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @user_posts = @user.posts
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper

  def fullname
    @user.first_name + " " + @user.last_name    
  end
  
end

app/views/comments/_comment.html.erb
<div id="comment-<%= comment.id %>">
  [<%= comment.created_at.strftime("%l:%M %p") %>]
  <%= comment.user_id %>: 
  <% if ( current_user && current_user.admin ) || ( current_user && current_user == comment.user ) %>
    <%= link_to "Delete", post_comment_path(@post, comment), method: :delete, remote: true, style: 'float: right' %>
  <% end %>
  <hr />
  <%= comment.body %>
</div>
<br>
<br>

app/views/comments/create.js.erb
$('#comments_pane').prepend("<%= j render @comment %>");
$('#comment_body').val("");

app/views/comments/destroy.js.erb
$('#comment-<%= @comment.id %>').fadeOut();

app/views/layouts/_alerts.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/layouts/_navbar.html.erb
<nav>
  <div class="container">
    <div class="nav">
      <% if current_user %>
        <div class="nav-left">
          <%= link_to current_user.username, root_path, class: "btn-home" %> <i id="verified" class="fas fa-certificate"></i>
        </div>
        <div>
        </div>
        <div class="nav-right">
          <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: "btn-signout" %>
        </div>
      <% else %>
        <div class="nav-left">
          Instachat
        </div>
        <div>
        </div>
        <div class="nav-right">
          <%= link_to 'Log in', new_user_session_path, class: "btn-signin" %>
          <%= link_to 'Sign up', new_user_registration_path, class: "btn-signup" %>
        </div>
      <% end %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Instachat</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.9.0/css/all.css">
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= render 'layouts/alerts' %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/_adminlinks.html.erb
<% if ( current_user && current_user.admin ) || (current_user && current_user.id == post.user_id ) %>
  <%= link_to "Edit", edit_post_path(post) %>
  <%= link_to "Destroy", post, method: :delete, data: { confirm: "Are you sure you want to delete this post?" } %>
<% end %>

app/views/pages/_comment.html.erb
<div id="comment-<%= comment.id %>">
  [<%= comment.created_at.strftime("%l:%M %p") %>]
  <%= comment.user_id %>:
  <%= comment.body %>
</div>
<br>
<br>

app/views/pages/home.html.erb
<h1>Homepage</h1>
<%= link_to "New Status", new_post_path %>
<div class="timeline">
  <div class="user-pane">
    <div class="user">
      <div class="avatar">
        <img class="avatar-img" src="https://cdn.pixabay.com/photo/2016/08/08/09/17/avatar-1577909_960_720.png" alt="avatar">
      </div>
      <div class="user-info">
        <h3><%= current_user.first_name %> <%= current_user.last_name %></h3>
        <h5>@<%= current_user.username.downcase %></h5>
      </div>
      <div>
        <% if current_user %>
            
        <% else %>
          
        <% end %>
      </div>
    </div>
  </div>
  <div class="posts-pane">
    <% @posts.each do |post| %>
      <div class="avatar">
        <img class="avatar-img" src="https://cdn.pixabay.com/photo/2016/08/08/09/17/avatar-1577909_960_720.png" alt="avatar">
      </div>
      <div class="post">
        <div class="post-header">
          <div class="header-left">
            <h3><%= post.user.first_name %> <%= post.user.last_name %></h3>
            <h5>@<%= post.user.username.downcase %> · <%= time_ago_in_words(post.created_at) %></h5>
          </div>
          <div class="header-right">
            <i class="fas fa-ellipsis-v"></i>
          </div>
        </div>
        <div class="post-body">
          <p><%= post.status %></p>
        </div>
        <div class="post-comments">

          <details>
            <summary><%= pluralize(post.comments.count, "Comment") %></summary>
            <div id="comments_pane">
              <% post.comments.each do |comment| %>
                <%= render 'pages/comment', comment: comment %>
              <% end %>
            </div> 
          </details>     
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/posts/_adminlinks.html.erb
<% if ( current_user && current_user.admin ) || (current_user && current_user.id == post.user_id ) %>
  <%= link_to "Edit", edit_post_path(post) %> // 
  <%= link_to "Destroy", post, method: :delete, data: { confirm: "Are you sure you want to delete this post?" } %>
<% end %>

app/views/posts/_form.html.erb
<%= simple_form_for @post, remote: true do |post| %>
  <%= post.input :status, label: false, maxlength: '255', placeholder: 'What\'s happening?' %>
  <%= post.submit 'Post Status', :class => 'post-submit-btn' %>
<% end %>

app/views/posts/_post.html.erb
<div class="avatar">
  <img class="avatar-img" src="https://cdn.pixabay.com/photo/2016/08/08/09/17/avatar-1577909_960_720.png" alt="avatar">
</div>
<div class="post" id="post-<%= post.id %>">
  <div class="post-header">
    <div class="header-left">
      <h3><%= link_to "#{post.user.first_name} #{post.user.last_name}", "/users/#{post.user.id}" %></h3>
      <h5>@<%= post.user.username.downcase %> · <%= time_ago_in_words(post.created_at) %></h5>
    </div>
    <div class="header-right">
      <i class="fas fa-ellipsis-v"></i>
    </div>
  </div>
  <div class="post-body">
    <p><%= post.status %></p>
  </div>
  <div class="post-comments">

    <details>
      <summary><%= pluralize(post.comments.count, "Comment") %></summary>
      <div id="comments_pane">
        <% post.comments.each do |comment| %>
          <%= render 'pages/comment', comment: comment %>
        <% end %>
      </div> 
    </details>     
  </div>
</div>

app/views/posts/create.js.erb
$('.posts_pane').prepend("<%= j render post %>");
$('#post_status').val("");

app/views/posts/destroy.js.erb
$('#post-<%= post.id %>').fadeOut();

app/views/posts/edit.html.erb
<h1>Edit Status</h1>

<%= render 'posts/form'  %>

app/views/posts/index.html.erb
<div class="timeline">

  <% if current_user %>
  
    <div class="user-pane">
      <div class="user">
        <div class="avatar">
          <img class="avatar-img" src="https://cdn.pixabay.com/photo/2016/08/08/09/17/avatar-1577909_960_720.png" alt="avatar">
        </div>
        <div class="user-info">
          <h3><%= current_user.first_name %> <%= current_user.last_name %></h3>
          <h5>@<%= current_user.username.downcase %></h5>
        </div>
        <div class="post-form">
          <% if current_user %>
            <%= render 'posts/form'  %>
          <% else %>
            
          <% end %>
        </div>
      </div>
    </div>
    <div></div>
    <div class="posts-pane">
      <% @posts.each do |post| %>
        <%= render 'posts/post', post: post %>
      <% end %>
    </div>

  <% else %>

    <div class="unrestricted-info">
      <img src="http://pa1.narvii.com/6509/4720addcf2b43a89af7be832950f9a4d4d14e056_00.gif" alt="lost">
      <h1><i class="fas fa-exclamation-circle"></i> Oh oh, you aren't a logged in</h1>
      <p>
        Log in or create an account and see what all the fun is about...
      </p> <br>
      <div>
        <%= link_to 'Log in', new_user_session_path, class: "btn-signin" %>
        <%= link_to 'Sign up', new_user_registration_path, class: "btn-signup" %>
      </div>
    </div>

  <% end %>
</div>

app/views/posts/new.html.erb
<h1>Create New Status</h1>

<%= render 'posts/form'  %>

app/views/posts/show.html.erb
<h1><%= @post.status %></h1>
<small><%= @post.created_at.strftime("%l:%M %p · %-m/%e/%y") %></small>
<br>
<br>
<br>

<% if current_user %>
  <%= form_with model: [@post, @comment], remote: true do |f| %>
    <%= f.text_field :body %>
    <%= f.submit "Comment" %>
  <% end %>  
<% else %>
  
<% end %>

<div id="comments_pane">
  <% @comments.each do |comment| %>
    <%= render 'comments/comment', comment: comment %>
  <% end %>
</div>

<%= link_to 'All Posts', posts_path %><br>
<%= render 'posts/adminlinks', post: @post %>

app/views/users/show.html.erb
<h1><%= fullname %></h1>
<%= @user.username %> <br>
<%= @user.description %>
<br>
<br>

<ul>
  <% @user_posts.each do |post| %>
    <li><%= post.status %></li>
    <%= time_ago_in_words(post.created_at) %>
    <br>
  <% end %>
</ul>
<%= link_to 'All Posts', posts_path %>